#ifndef DEFINES_GLSL
#define DEFINES_GLSL

#define pi 3.141592653589793f
#define MAX_NUM_JOINTS 256

#define WORKFLOW_METALLIC_ROUGHNESS 0
#define WORKFLOW_SPECULAR_GLOSINESS 1
#define MIN_ROUGHNESS 0.04f

#define SPOT_LIGHTING_TYPE_CIRCLE 0
#define SPOT_LIGHTING_TYPE_SQUARE 1

#endif