#!/usr/bin/env python3
"""
spv_to_header.py — Convert compiled SPIR-V files into a single C++ header.

Usage:
    python spv_to_header.py --output <header.h> <file1.spv> [<file2.spv> ...]

The lookup key for each SPV file is derived from its path as:
    <parent_directory>/<filename>
e.g. ".../spv/deferredGraphics/base/baseVert.spv"  ->  "base/baseVert.spv"

The generated header provides:
    namespace moon::shaders::embedded {
        inline std::span<const uint32_t> lookup(std::string_view key);
    }
"""

import argparse
import os
import struct
import sys
from pathlib import Path


def c_identifier(name: str) -> str:
    """Convert a string like 'base/baseVert.spv' to a valid C identifier."""
    return name.replace('/', '_').replace('.', '_').replace('-', '_')


def spv_to_uint32(path: Path) -> list[int]:
    data = path.read_bytes()
    if len(data) % 4 != 0:
        raise ValueError(f"{path}: size {len(data)} is not a multiple of 4")
    count = len(data) // 4
    return list(struct.unpack(f'<{count}I', data))


def write_header(output: Path, spv_files: list[Path]) -> None:
    shaders = []
    for spv in spv_files:
        # Key = last two path components, forward-slash separated
        key = f"{spv.parent.name}/{spv.name}"
        var = c_identifier(f"{spv.parent.name}_{spv.stem}")
        words = spv_to_uint32(spv)
        shaders.append((key, var, words))

    output.parent.mkdir(parents=True, exist_ok=True)

    with output.open('w', newline='\n') as f:
        f.write("// Auto-generated by scripts/spv_to_header.py — do not edit\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n")
        f.write("#include <span>\n")
        f.write("#include <string_view>\n\n")
        f.write("namespace moon::shaders::embedded {\n\n")

        # Emit each shader array
        for key, var, words in shaders:
            f.write(f"// {key}  ({len(words) * 4} bytes)\n")
            f.write(f"inline constexpr uint32_t {var}[] = {{\n")
            for i, w in enumerate(words):
                if i % 8 == 0:
                    f.write("    ")
                f.write(f"0x{w:08x}")
                if i < len(words) - 1:
                    f.write(", ")
                if (i + 1) % 8 == 0 or i == len(words) - 1:
                    f.write("\n")
            f.write("};\n\n")

        # Emit lookup function
        f.write("inline std::span<const uint32_t> lookup(std::string_view key) {\n")
        for key, var, words in shaders:
            f.write(f'    if (key == "{key}") ')
            f.write(f"return {{{var}, {len(words)}u}};\n")
        f.write("    return {};\n")
        f.write("}\n\n")
        f.write("} // namespace moon::shaders::embedded\n")

    print(f"[spv_to_header] Generated {output} ({len(shaders)} shaders)")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path,
                        help="Output header file path")
    parser.add_argument("spv_files", nargs="+", type=Path,
                        help="Input .spv files")
    args = parser.parse_args()

    missing = [p for p in args.spv_files if not p.exists()]
    if missing:
        for p in missing:
            print(f"[spv_to_header] ERROR: not found: {p}", file=sys.stderr)
        sys.exit(1)

    write_header(args.output, args.spv_files)


if __name__ == "__main__":
    main()
